import 'models.dart';

List<UiSpot> demoSpots() => [
  const UiSpot(
    kind: SpotKind.l2_open_fold,
    hand: 'A\u2660K\u2660',
    pos: 'BTN',
    stack: '20bb',
    action: 'open',
  ),
  const UiSpot(
    kind: SpotKind.l2_open_fold,
    hand: '7\u26637\u2666',
    pos: 'UTG',
    stack: '12bb',
    action: 'fold',
  ),
  const UiSpot(
    kind: SpotKind.l2_threebet_push,
    hand: 'A\u2666Q\u2666',
    pos: 'SB',
    vsPos: 'BTN',
    stack: '18bb',
    action: 'jam',
  ),
  const UiSpot(
    kind: SpotKind.l2_threebet_push,
    hand: 'K\u2663J\u2663',
    pos: 'BB',
    vsPos: 'SB',
    stack: '25bb',
    action: 'fold',
  ),
  const UiSpot(
    kind: SpotKind.l2_limped,
    hand: 'A\u26639\u2663',
    pos: 'BTN',
    limpers: 'UTG',
    stack: '15bb',
    action: 'iso',
  ),
  const UiSpot(
    kind: SpotKind.l2_limped,
    hand: '7\u26606\u2660',
    pos: 'CO',
    limpers: 'UTG, MP',
    stack: '25bb',
    action: 'overlimp',
  ),
  const UiSpot(
    kind: SpotKind.l2_limped,
    hand: 'Q\u26664\u2666',
    pos: 'SB',
    limpers: 'BTN',
    stack: '18bb',
    action: 'fold',
  ),
  const UiSpot(
    kind: SpotKind.l4_icm,
    hand: 'A\u26605\u2660',
    pos: 'SB',
    vsPos: 'BB',
    stack: '10bb',
    action: 'jam',
  ),
  const UiSpot(
    kind: SpotKind.l4_icm,
    hand: 'K\u26662\u2666',
    pos: 'BTN',
    vsPos: 'SB',
    stack: '9bb',
    action: 'fold',
  ),
  const UiSpot(
    kind: SpotKind.l2_open_fold,
    hand: 'Q\u2660Q\u2665',
    pos: 'CO',
    stack: '30bb',
    action: 'open',
  ),
  const UiSpot(
    kind: SpotKind.l4_icm,
    hand: 'J\u2663T\u2663',
    pos: 'BB',
    vsPos: 'SB',
    stack: '6bb',
    action: 'fold',
  ),
  const UiSpot(
    kind: SpotKind.l2_threebet_push,
    hand: '9\u26609\u2666',
    pos: 'BB',
    vsPos: 'CO',
    stack: '14bb',
    action: 'jam',
  ),
];
