// Autogenerated single-source truth for Tap-to-Explain tokens; append-only.
const List<String> tokenRegistry = [
  'PFA',
  'SRP',
  'Fv3B',
  '4B',
  'Fv75',
  'Fv50',
  'AFq',
  'DB',
  'EV',
  'GTO',
  'XR',
  'X/R',
];
